trigger:
  branches:
    include:
      - "*"
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: bitbar-runner

stages:
  - stage: Make_extension
    jobs:
      - job:
        steps:
          - task: UseGitVersion@5
            displayName: Set Git Version
            inputs:
              versionSpec: '5.x'
              updateAssemblyInfo: false
              useConfigFile: true
              configFilePath: 'GitVersion.yml'

          - script: |
              npm run release
            displayName: 'npm install, build, PackageAzureDevOpsExtension'

          - task: CopyFiles@2
            displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
            inputs:
              Contents: "**/*.vsix"
              TargetFolder: "$(Build.ArtifactStagingDirectory)"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "$(artifactName)"
              publishLocation: "Container"

  - stage: Publish_extension
    jobs:
      - job:
        steps:
          - task: TfxInstaller@3
            inputs:
              version: "v0.7.x"

          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "$(artifactName)"
              downloadPath: "$(System.DefaultWorkingDirectory)"
              
          - task: PublishAzureDevOpsExtension@3
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'Visual Studio Marketplace'
              fileType: 'vsix'
              vsixFile: '**/*.vsix'
              publisherId: '$(publisherID)'
              extensionId: '$(extensionID)'
              extensionName: '$(extensionName)'
              updateTasksVersion: false
              extensionVisibility: 'private'
              extensionPricing: 'free'
